/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all posts */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description When provided, populates the userVote field in responses */
                    "X-User-Id"?: components["parameters"]["optionalUserId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of posts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PostResponse"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a post */
        post: {
            parameters: {
                query?: never;
                header: {
                    "X-User-Id": components["parameters"]["userId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PostRequest"];
                };
            };
            responses: {
                /** @description Post created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PostResponse"];
                    };
                };
                /** @description Forum not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a post by ID */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description When provided, populates the userVote field in responses */
                    "X-User-Id"?: components["parameters"]["optionalUserId"];
                };
                path: {
                    id: components["parameters"]["postId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Post found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PostResponse"];
                    };
                };
                /** @description Post not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Update a post */
        put: {
            parameters: {
                query?: never;
                header: {
                    "X-User-Id": components["parameters"]["userId"];
                };
                path: {
                    id: components["parameters"]["postId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PostRequest"];
                };
            };
            responses: {
                /** @description Post updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PostResponse"];
                    };
                };
                /** @description Post or forum not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete a post */
        delete: {
            parameters: {
                query?: never;
                header: {
                    "X-User-Id": components["parameters"]["userId"];
                };
                path: {
                    id: components["parameters"]["postId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Post deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Post not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{id}/upvote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upvote a post (toggle - calling again removes the vote) */
        post: {
            parameters: {
                query?: never;
                header: {
                    "X-User-Id": components["parameters"]["userId"];
                };
                path: {
                    id: components["parameters"]["postId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Vote recorded or removed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VoteResponse"];
                    };
                };
                /** @description Post not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{id}/downvote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Downvote a post (toggle - calling again removes the vote) */
        post: {
            parameters: {
                query?: never;
                header: {
                    "X-User-Id": components["parameters"]["userId"];
                };
                path: {
                    id: components["parameters"]["postId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Vote recorded or removed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VoteResponse"];
                    };
                };
                /** @description Post not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all forums */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of forums */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ForumResponse"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a forum */
        post: {
            parameters: {
                query?: never;
                header: {
                    "X-User-Id": components["parameters"]["userId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ForumRequest"];
                };
            };
            responses: {
                /** @description Forum created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ForumResponse"];
                    };
                };
                /** @description Forum name already taken */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forums/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a forum by name */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: components["parameters"]["forumName"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Forum found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ForumResponse"];
                    };
                };
                /** @description Forum not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Update a forum */
        put: {
            parameters: {
                query?: never;
                header: {
                    "X-User-Id": components["parameters"]["userId"];
                };
                path: {
                    name: components["parameters"]["forumName"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ForumRequest"];
                };
            };
            responses: {
                /** @description Forum updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ForumResponse"];
                    };
                };
                /** @description Forum not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete a forum */
        delete: {
            parameters: {
                query?: never;
                header: {
                    "X-User-Id": components["parameters"]["userId"];
                };
                path: {
                    name: components["parameters"]["forumName"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Forum deleted (posts, votes, and subscriptions cascade-deleted) */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forum not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forums/{name}/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all posts in a forum */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description When provided, populates the userVote field in responses */
                    "X-User-Id"?: components["parameters"]["optionalUserId"];
                };
                path: {
                    name: components["parameters"]["forumName"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of posts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PostResponse"][];
                    };
                };
                /** @description Forum not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forums/{name}/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Subscribe to a forum */
        post: {
            parameters: {
                query?: never;
                header: {
                    "X-User-Id": components["parameters"]["userId"];
                };
                path: {
                    name: components["parameters"]["forumName"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Subscribed (idempotent - no-op if already subscribed) */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forum not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Unsubscribe from a forum */
        delete: {
            parameters: {
                query?: never;
                header: {
                    "X-User-Id": components["parameters"]["userId"];
                };
                path: {
                    name: components["parameters"]["forumName"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unsubscribed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forum not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all forums the authenticated user is subscribed to */
        get: {
            parameters: {
                query?: never;
                header: {
                    "X-User-Id": components["parameters"]["userId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of subscribed forums */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ForumResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all comments for a post (newest-first) */
        get: {
            parameters: {
                query: {
                    postId: string;
                };
                header?: {
                    /** @description When provided, populates the userVote field in responses */
                    "X-User-Id"?: components["parameters"]["optionalUserId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of comments */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommentResponse"][];
                    };
                };
                /** @description postId missing */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Post not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create a comment */
        post: {
            parameters: {
                query?: never;
                header: {
                    "X-User-Id": components["parameters"]["userId"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CommentRequest"];
                };
            };
            responses: {
                /** @description Comment created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommentResponse"];
                    };
                };
                /** @description postId missing */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Post not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a comment by ID */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description When provided, populates the userVote field in responses */
                    "X-User-Id"?: components["parameters"]["optionalUserId"];
                };
                path: {
                    id: components["parameters"]["commentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Comment found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommentResponse"];
                    };
                };
                /** @description Comment not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Update a comment */
        put: {
            parameters: {
                query?: never;
                header: {
                    "X-User-Id": components["parameters"]["userId"];
                };
                path: {
                    id: components["parameters"]["commentId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CommentRequest"];
                };
            };
            responses: {
                /** @description Comment updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommentResponse"];
                    };
                };
                /** @description Not the author */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Comment not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete a comment (cascade-deletes its votes) */
        delete: {
            parameters: {
                query?: never;
                header: {
                    "X-User-Id": components["parameters"]["userId"];
                };
                path: {
                    id: components["parameters"]["commentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Comment deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not the author */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Comment not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/{id}/upvote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upvote a comment (toggle - calling again removes the vote) */
        post: {
            parameters: {
                query?: never;
                header: {
                    "X-User-Id": components["parameters"]["userId"];
                };
                path: {
                    id: components["parameters"]["commentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Vote recorded or removed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VoteResponse"];
                    };
                };
                /** @description Comment not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/{id}/downvote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Downvote a comment (toggle - calling again removes the vote) */
        post: {
            parameters: {
                query?: never;
                header: {
                    "X-User-Id": components["parameters"]["userId"];
                };
                path: {
                    id: components["parameters"]["commentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Vote recorded or removed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VoteResponse"];
                    };
                };
                /** @description Comment not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PostRequest: {
            title: string;
            content: string;
            forumName: string;
        };
        PostResponse: {
            id?: string;
            title?: string;
            content?: string;
            userId?: string;
            forumName?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            upvoteCount?: number;
            downvoteCount?: number;
            commentCount?: number;
            userVote?: components["schemas"]["VoteType"];
        };
        ForumRequest: {
            name: string;
            description: string;
        };
        ForumResponse: {
            name?: string;
            description?: string;
            createdBy?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            subscriberCount?: number;
        };
        CommentRequest: {
            postId: string;
            content: string;
        };
        CommentResponse: {
            id?: string;
            postId?: string;
            parentCommentId?: string | null;
            content?: string;
            userId?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            upvoteCount?: number;
            downvoteCount?: number;
            userVote?: components["schemas"]["VoteType"];
        };
        VoteResponse: {
            userVote?: components["schemas"]["VoteType"];
        };
        /** @enum {string|null} */
        VoteType: "UPVOTE" | "DOWNVOTE" | null;
    };
    responses: never;
    parameters: {
        userId: string;
        /** @description When provided, populates the userVote field in responses */
        optionalUserId: string;
        postId: string;
        forumName: string;
        commentId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
